### ISSUE TITLE
Using deps of java 8 under java 7

### ISSUE THREAD

**Issue by RonZamkadny** [kxbmap/configs#17]
Error:scalac: missing or invalid dependency detected while loading class file 'ConfigsInstances.class'.
Could not access type Duration in value java.time,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'ConfigsInstances.class' was compiled against an incompatible version of java.time.

**Comment by kxbmap** [comment]
Java 7 support was dropped in 0.4.x.
