### ISSUE TITLE
Instances for single field value classes

### ISSUE THREAD

**Issue by pkoryzna** [kxbmap/configs#26]
Oftentimes I find myself creating a lot of value classes to wrap primitives for better type safety, e.g.

```scala
case class BitOffset(n: Int) extends AnyVal
case class Temperature(celsius: Int) extends AnyVal
// so on and so forth
```

This, however turns out to be slightly annoying when loading those as config values - the automatic derivation expects the values to be passes as fields in the config and leads to runtime errors like:  `bit-offset has type NUMBER rather than OBJECT`

So far I work this around by making my own instances for those types but I can imagine this could get troublesome and boilerplate-y for applications that use a lot of them:

```scala
object ConfigsInstances {

  def valueClassWrapperInstance[C, T](constr: T => C): Configs[C] = Configs.from { (conf, path) =>
    Configs[T].get(conf, path).map(constr)
  }
  implicit val BitOffsetInstance: Configs[BitOffset] = valueClassWrapperInstance(BitOffset)
// imagine more implicits here ;-)

```

I believe that some sort of optional import for those cases would be a convenient feature.

**Comment by kxbmap** [comment]
Released 0.5.0, please check it out.
