### ISSUE TITLE
Default naming strategy should be Identity

### ISSUE THREAD

**Issue by winitzki** [kxbmap/configs#52]
The behavior of `kxbmap:configs` has changed after 0.4 in that the default naming strategy expects camel-case names to be translated into dash-separated names. For example, `case class Data(baseUrl: String = "/base")` will silently fail to parse the config such as

```
baseUrl = "/service/user"
```

because it expects the name in the config to be `base-url`. Instead it will  assign the default value `/base` to the config element. This leads to bugs that are not easy to detect.

This breaks code upgraded from 0.3.x . A workaround is to insert code such as

```scala
  implicit def configKeyNaming[C]: ConfigKeyNaming[C] = ConfigKeyNaming.identity[C]
```

However,  it is not always easy to guess where to insert this workaround code. It should be inserted just before the config is parsed into a specific case class. But sometimes the code parses configs of different classes at the same time, and it leads to confusion. The reason is that the naming strategy is used for auto-generating the `ConfigReader` for the given case class. But it is not always clear where this auto-generation takes place in the user code.

I think it would be better if the default naming strategy were `identity`, and/or if the API were changed so that it is easier to figure out where the implicit naming strategy should be inserted into the code. 

Alternatively, a new API should be added to parse the config while giving a specific naming strategy as an implicit argument.

**Comment by kxbmap** [comment]
Thank you for the feedback.

The default naming strategy was changed in 0.4 because hyphen-separated keys were encouraged in the HOCON documentation. I have no intention of changing it for now.

When changing the naming strategy, expected to define like the following in the companion object.
```scala
object Data {
  implicit val dataConfigKeyNaming: ConfigKeyNaming[Data] = ConfigKeyNaming.identity[Data]
}
```
Also, since version 0.6.0, a function to detect superfluous keys has been added.
If you define like the following:
```scala
object Data {
  implicit val dataConfigKeyNaming: ConfigKeyNaming[Data] =
    ConfigKeyNaming.hyphenSeparated[Data].withFailOnSuperfluousKeys
}
```
You will get an error message like ` Superfluous key(s) found: baseUrl (did you mean base-url?)`

But, I understand that the current API is complex, so I am considering redesigning the API.

**Comment by winitzki** [comment]
Thank you for your reply.

I understand why the functionality was changed. I am not going to downgrade to 0.3 because a lot of good new functionality was added in the recent versions of this library. I just have two comments:

- If I need a config naming strategy = identity, do I have to define this impilcit only in the companion object of the top-level case class or in every companion object of every case class? If so, this is a lot of boilerplate and I would rather go with adding this workaround:

```scala
implicit def configKeyNaming[C]: ConfigKeyNaming[C] = ConfigKeyNaming.identity[C]
```

- Is the option `withFailOnSuperfluousKeys` active by default or not? If it is not active by default, then the situation with the silent bug will persist. I would consider activating this option by default with your `hyphenSeparated` naming strategy.

**Comment by kxbmap** [comment]
You need to define implicit value for all case classes.
Another option is to define it in a package object once, or insert it in the proper position as you are doing.

```scala
package com

package object example {
  private[example] implicit def pacakgeLevelConfigKeyNaming[C]: ConfigKeyNaming[C] = 
    ConfigKeyNaming.identity[C].withFailOnSuperfluousKeys
}
```

`withFailOnSuperfluousKeys` is off by default.

**Comment by winitzki** [comment]
Thank you for explanations.
