### ISSUE TITLE
Version 6.0.0 / Scala 2.11 sometimes fails to find default values for case class attributes

### ISSUE THREAD

**Issue by zzeekk** [kxbmap/configs#53]
Configs version 6.0.0 with scala 2.11 has sometimes problems finding default values of case classes. It works with scala 2.12. I had the following cases:

- a case class at 2nd level has an attribute "xyz: Option[Boolean] = Some(true)". A config without this attribute is parsed as "xyz = None", not respecting its default value.
- a case class at 2nd level has an attribute "xyz: Boolean = true". A config without this attribute throws an error that configuration for attribute "xyz" is missing. It seems that Configs doesn't know about its default value.

The strange thing about these errors is that they are not reproducible in unit tests of this project. I guess that it has to do with the numbers of macros that are generated in the project, and that scala optimizes loading of corresponding type metadata.

**Comment by zzeekk** [comment]
PR #51 fixes the Problem. Would it be possible to release a bugfix release with this patch soon?

**Comment by kxbmap** [comment]
Thank you for the report.
Merged #51 and released version 0.6.1.
