### ISSUE TITLE
Add support for Map that preserves insertion order

### ISSUE THREAD

**Issue by JayChandler** [kxbmap/configs#8]
Currently there is just support for Map that doesn't preserve the insertion order of the config items.
<pre>
config {
	items{
		"key1" =  "Hello"
		"key2" =  "World"
	}
}
</pre> 
When u call this code its not garuanteed that the keys are in the order they have been defined
```java
 println(config.get[Map[String, String]]("config.items"))
```
Maybe add support for ListMap or TreeMap or any kind of Map which preserves insertion order ?

**Comment by kxbmap** [comment]
`configs` is wrapper for `config`, and `config` does not preserves insertion order of object keys.
if `config` is support it, also `configs` can support.

And `ListMap` preserves insertion order, but `TreeMap` does not.
`TreeMap` sorts entries by key.
So, `configs` may support `TreeMap`.

If you just need `TreeMap`, workaround is:

```scala
println(TreeMap.empty ++ config.get[Map[String, String]]("config.items"))
```

**Comment by kxbmap** [comment]
Add support for subclasses of Map on branch `master`.

You can write the following:

```scala
println(config.get[TreeMap[String, String]]("config.items"))
```

also can:

```scala
println(config.get[ListMap[String, String]]("config.items"))
```

But the returning `ListMap` does not preserve definition order.
On branch `preserve-iteration-order`, it preserves not definition order but iteration order of `ConfigObject`. If `config` add support for definition order iteration, I will merge this branch.

**Comment by kxbmap** [comment]
There is workaround.

First, write config file like the following:
```hocon
config {
    items = [
        { "key1" =  "Hello" }
        { "key2" =  "World" }
    ]
}
```
then define custom `Configs` instance:
```scala
implicit val listMapConfigs: Configs[ListMap[String, String]] =
  Configs[List[Map[String, String]]].map(_.foldLeft(ListMap.empty[String, String])(_ ++ _))
```
and then:
```scala
println(config.get[ListMap[String, String]]("config.items"))
```
