### ISSUE TITLE
Create Java 7 version

### ISSUE THREAD

**Issue by tomduhourq** [kxbmap/configs#9]
The actual library is intended for JDK 1.8, it would be nice to make it compile to Java 7, too.

**Comment by kxbmap** [comment]
Current version of configs depends on Typesafe config 1.3 that supports Java 8 only.
So it is not easy to build for Java 7.
I want to support if there is a good idea to support previous Java versions.

In version 0.2.x, supporting Java 7.
https://github.com/kxbmap/configs/tree/v0.2.x

**Comment by kxbmap** [comment]
Working on this branch:
https://github.com/kxbmap/configs/tree/v0.3.x-java7

* Downgrade to config 1.2.1
* Remove instances for Java 8 class (java.time.Duration)
* Remove instances for config 1.3 class (ConfigMemorySize)
* Ignore some tests due to change of behavior of config

**Comment by tomduhourq** [comment]
Thanks for making this branch. The idea for Java 7 is that many companies (mine for example) are currently working with Java 7 in production, with plans but not yet decided to migrate to 8.

**Comment by kxbmap** [comment]
Published `configs-java7` module. It will sync to Maven Central in few hours.

You can use configs with Java 7 as the follows:
```scala
libraryDependencies += "com.github.kxbmap" %% "configs-java7" % "0.3.0"
```
